aA = int(input( "Give me the first number:" ))
bB = int(input( "Give me the seond number:" ))
print ("ThanK you !")
print (f"{aA} + {bB} = {aA + bB}")
print (f"{aA} - {bB} = {aA - bB}")
print (f"{aA} * {bB} = {aA * bB}")
print (f"{aA} ** {bB} = {aA ** bB}")
print (f"{aA} / {bB} = {aA / bB}")
print (f"{aA} // {bB} = {aA // bB}")
print (f"{aA} % {bB} = {aA % bB}")